name: SmartInvs
version: 1.2.7
description: Inventory API for your Bukkit Plugins.
api-version: 1.17
author: MinusKube
website: https://github.com/MinusKube/SmartInvs
main: fr.minuskube.inv.SmartInvsPlugin