name: SmartInvs
version: '${project.version}'
description: Updated inventory API for your Bukkit Plugins.
api-version: 1.17
author: MinusKube
authors:
  - MinusKube
  - MCmitNoah
website: https://github.com/MinusKube/SmartInvs
main: io.github.leguan16.smartinvs.SmartInvsPlugin